export const NUMBER_0_INPUT = "NUMBER_0_INPUT";
export const NUMBER_1_INPUT = "NUMBER_1_INPUT";
export const NUMBER_2_INPUT = "NUMBER_2_INPUT";
export const NUMBER_3_INPUT = "NUMBER_3_INPUT";
export const NUMBER_4_INPUT = "NUMBER_4_INPUT";
export const NUMBER_5_INPUT = "NUMBER_5_INPUT";
export const NUMBER_6_INPUT = "NUMBER_6_INPUT";
export const NUMBER_7_INPUT = "NUMBER_7_INPUT";
export const NUMBER_8_INPUT = "NUMBER_8_INPUT";
export const NUMBER_9_INPUT = "NUMBER_9_INPUT";
export const NUMBER_SUBMIT_INPUT = "NUMBER_SUBMIT_INPUT";
export const NUMBER_CANCEL_INPUT = "NUMBER_CANCEL_INPUT";

export const NUMBER_BUTTON_ACTION = {
  NUMBER_0_INPUT,
  NUMBER_1_INPUT,
  NUMBER_2_INPUT,
  NUMBER_3_INPUT,
  NUMBER_4_INPUT,
  NUMBER_5_INPUT,
  NUMBER_6_INPUT,
  NUMBER_7_INPUT,
  NUMBER_8_INPUT,
  NUMBER_9_INPUT,
  NUMBER_CANCEL_INPUT,
  NUMBER_SUBMIT_INPUT
};
